#! /bin/sh

module="scull"
device="scull"
mode="664"

module_faulty="faulty"
device_faulty="faulty"

#group="staff"


case "$1" in
  start)

    # Loading hello module
    echo "Loading hello module"
    modprobe hello || exit 1
    
    # Loading scull module
    echo "Loading scull module"
    modprobe $module || exit 1 

    # retrieve major number
    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
    
    rm -f /dev/${device}[0-3]
    mknod /dev/${device}0 c $major 0
    mknod /dev/${device}1 c $major 1
    mknod /dev/${device}2 c $major 2
    mknod /dev/${device}3 c $major 3
    #chgrp $group /dev/${device}[0-3] 
    chmod $mode  /dev/${device}[0-3]
    
    rm -f /dev/${device}pipe[0-3]
    mknod /dev/${device}pipe0 c $major 4
    mknod /dev/${device}pipe1 c $major 5
    mknod /dev/${device}pipe2 c $major 6
    mknod /dev/${device}pipe3 c $major 7
    #chgrp $group /dev/${device}pipe[0-3]
    chmod $mode  /dev/${device}pipe[0-3]
    
    rm -f /dev/${device}single
    mknod /dev/${device}single  c $major 8
    #chgrp $group /dev/${device}single
    chmod $mode  /dev/${device}single

    rm -f /dev/${device}uid
    mknod /dev/${device}uid   c $major 9
    #chgrp $group /dev/${device}uid
    chmod $mode  /dev/${device}uid

    rm -f /dev/${device}wuid
    mknod /dev/${device}wuid  c $major 10
    #chgrp $group /dev/${device}wuid
    chmod $mode  /dev/${device}wuid

    rm -f /dev/${device}priv
    mknod /dev/${device}priv  c $major 11
    #chgrp $group /dev/${device}priv
    chmod $mode  /dev/${device}priv


    #Loading faulty module
    echo "Loading faulty module"
    modprobe $module_faulty || exit 1

    major_faulty=$(awk "\$2==\"$module_faulty\" {print \$1}" /proc/devices)

    mknod /dev/${device_faulty} c $major_faulty 0
    #chgrp $group /dev/${device}
    chmod $mode  /dev/${device_faulty}

    ;;

    


  stop)
    echo "Unload hello module"
    rmmod hello || exit 1

    echo "Unload scull module"
    rmmod $module || exit 1

    rm -f /dev/${device}[0-3] 
    rm -f /dev/${device}priv
    rm -f /dev/${device}pipe[0-3]
    rm -f /dev/${device}single
    rm -f /dev/${device}uid
    rm -f /dev/${device}wuid


    echo "Unload faulty module"
    rmmod $module_faulty || exit 1
    rm -f /dev/${device_faulty}    

    ;;

  *)
    echo "Usage: $0 {srart|stop}"
  exit 1
esac


exit 0
