#! /bin/sh

module="aesdchar"
device="aesdchar"
mode="666"


set -e
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

case "$1" in
  start)
    # Loading aesdchar module
    echo "Loading aesdchar module"
    modprobe $module || exit 1
    
    # retrieve major number
    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
    
    rm -f /dev/${device}
    mknod /dev/${device} c $major 0 
    chmod $mode /dev/${device}
    chgrp $group /dev/${device}
    ;;

  stop)
    # unloading aesdchar module
    echo "Unload aesdchar module"
    rmmod $module || exit 1
    rm -f /dev/${device}
    ;;

  *)
    echo "Usage: $0 {srart|stop}"
  exit 1
esac


exit 0
